### ISSUE TITLE
Doesn't work.

### ISSUE THREAD

**Issue by Mine335** [ayes-web/CounterBot#5]
Hi. I wrote my token and the channel id, started the bot by sending a number with another account, but the bot did not start counting.

**Comment by ayes-web** [comment]
Hi can you contact me on any other platforms?
Would be easier to help you there
https://pastebin.com/Dts7XMaF

**Comment by ayes-web** [comment]
Actually i just googled and it seems that discord.py doesn't support self bots anymore: https://stackoverflow.com/a/67341709
